DROP DATABASE IF EXISTS projeto;
CREATE DATABASE projeto;
USE projeto;

-- Tabela de usuários para acesso ao sistema
CREATE TABLE usr (
    USRID INT PRIMARY KEY AUTO_INCREMENT,
    USRNOME VARCHAR(30),
    USRSENHA VARCHAR(20),
    USRCRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USRATIVO INT DEFAULT 1
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into usr (USRNOME, USRSENHA) values ('Andrew', 'senha'), ('Luan', 'senha'), ('Braian', 'senha');

-- DO SUPPORT
DROP TABLE IF EXISTS ver;
CREATE TABLE  ver (
  VERVERSAO int(11) PRIMARY KEY AUTO_INCREMENT,
  VERNOME char(15) DEFAULT '',
  VERLIBERAC datetime DEFAULT '1899-12-30 00:00:00',
  VERVALIDAD datetime DEFAULT '1899-12-30 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Tabela de categorias dos módulos
CREATE TABLE ctm (
    CTMID INT PRIMARY KEY AUTO_INCREMENT,
    CTMDESC VARCHAR(10) NOT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO ctm (CTMDESC) VALUES ('ERP'), ('WHATSAPP'), ('SUB-MODULO');


-- Tabela de módulos
CREATE TABLE mdl (
    MDLMODULO INT PRIMARY KEY,
    MDLDESC VARCHAR(30),
    MDLVERSAO int(11),
    MDLCATEGORIA INT,
    CONSTRAINT fk_mod_ctm FOREIGN KEY (MDLCATEGORIA) REFERENCES ctm (CTMID),
    CONSTRAINT fk_mod_ver FOREIGN KEY (MDLVERSAO) REFERENCES ver (VERVERSAO)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Tabela de clientes principais
CREATE TABLE cl1 (
    CL1CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CL1NOME VARCHAR(50)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Tabela de tipos de estabelecimentos
CREATE TABLE cl4 (
    CL4TIPO INT PRIMARY KEY AUTO_INCREMENT,
    CL4DESC VARCHAR(20) NOT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO cl4 (CL4DESC) VALUES ('Fabrica'), ('Loja'), ('Matriz');

-- Tabela de shoppings
CREATE TABLE cl5 (
    CL5SHOPPING INT PRIMARY KEY AUTO_INCREMENT,
    CL5APELIDO VARCHAR(10) DEFAULT '',
    CL5DESC VARCHAR(40) NOT NULL,
    CL5ATACADO INT DEFAULT 0,
    CL5LOCAL VARCHAR(30) DEFAULT ''
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO cl5 (CL5APELIDO, CL5DESC, CL5ATACADO) VALUES ('CCF', 'Centro de Compras Farroupilha', 0), 
('FAC', 'Farroupilhas center', 1), 
('585', '', 1), 
('CCB', 'Centro de Compras Bom Principio', 0), 
('Litoral', 'Shopping Litoral SC', 0);

-- Tabela de estabelecimentos, matriz ou filiais de um cliente
CREATE TABLE cl2 (
    CL2CLIENTE INT,
    CL2EST INT PRIMARY KEY,
    CL2TIPOEST INT,
    CL2SHOPPING INT,
    CL2CNPJ VARCHAR(18) DEFAULT '',
    CL2FANTASIA VARCHAR(50) NOT NULL,
    CL2GERENTE VARCHAR(50) DEFAULT '',
    CL2CTT VARCHAR(15) DEFAULT '',
    CL2OBS LONGTEXT,
    CL2ACESSO LONGTEXT,
    CL2ENDER LONGTEXT,
    CL2FIM TIMESTAMP,
    CL2INICIO TIMESTAMP,
    CONSTRAINT fk_cl2_cl1 FOREIGN KEY (CL2CLIENTE) REFERENCES cl1 (CL1CLIENTE),
    CONSTRAINT fk_cl2_cl4 FOREIGN KEY (CL2TIPOEST) REFERENCES cl4 (CL4TIPO),
    CONSTRAINT fk_cl2_cl5 FOREIGN KEY (CL2SHOPPING) REFERENCES cl5 (CL5SHOPPING)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Tabela de módulos e versões dos estabelecimentos dos clientes
CREATE TABLE cl3 (
    CL3EST INT,
    CL3MODULO INT,
    CL3VERSAO int(11) NOT NULL,
    CL3ATUALIZ VARCHAR(10) DEFAULT '',
    CL3RESPATT INT DEFAULT NULL,
    CL3RESP INT NOT NULL,
    PRIMARY KEY (CL3EST, CL3MODULO),
    CONSTRAINT fk_cl3_cl2 FOREIGN KEY (CL3EST) REFERENCES cl2 (CL2EST),
    CONSTRAINT fk_cl3_mdl FOREIGN KEY (CL3MODULO) REFERENCES mdl (MDLMODULO),
    CONSTRAINT fk_cl3_ver FOREIGN KEY (CL3VERSAO) REFERENCES ver (VERVERSAO),
    CONSTRAINT fk_cl3_responsavel FOREIGN KEY (CL3RESP) REFERENCES usr (USRID),
    CONSTRAINT fk_cl3_responsavel_atualizacao FOREIGN KEY (CL3RESPATT) REFERENCES usr (USRID)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Tabela de anotações
CREATE TABLE nta (
    NTAID INT PRIMARY KEY AUTO_INCREMENT,
    NTATITULO VARCHAR(20) NOT NULL,
    TNAINTRO VARCHAR(60) DEFAULT '',
    NTACONTEUDO LONGTEXT,
    NTACRIADOR INT NOT NULL,
    NTACRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NTALINK DECIMAL(1,0) DEFAULT 0,
    NTALINKDIR VARCHAR(250) DEFAULT '#',
    CONSTRAINT fk_nta_criador FOREIGN KEY (NTACRIADOR) REFERENCES usr (USRID)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;
