DROP TABLE IF EXISTS `oryxsupport`.`bkp`;
CREATE TABLE  `oryxsupport`.`bkp` (
  `BKPESTAB` int(11) NOT NULL,
  `BKPHORA` datetime DEFAULT '1899-12-30 00:00:00',
  `BKPLOCAL` char(255) DEFAULT '0',
  `BKPDATABKP` datetime DEFAULT '1899-12-30 00:00:00',
  PRIMARY KEY (`BKPESTAB`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`cf1`;
CREATE TABLE  `oryxsupport`.`cf1` (
  `CF1CLIENTE` char(14) NOT NULL,
  `CF1NOME` char(50) DEFAULT '',
  `CF1ATIVO` decimal(1,0) DEFAULT '0',
  `CF1VALIDAD` datetime DEFAULT '2999-12-30 00:00:00',
  `CF1ABERT` datetime DEFAULT '1899-12-30 00:00:00',
  `CF1LICENCA` char(5) NOT NULL,
  `CF1AUTORIZ` char(6) NOT NULL,
  PRIMARY KEY (`CF1CLIENTE`),
  UNIQUE KEY `CF1LICENCA` (`CF1LICENCA`),
  UNIQUE KEY `CF1AUTORIZ` (`CF1AUTORIZ`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`dc0`;
CREATE TABLE  `oryxsupport`.`dc0` (
  `DC0ARQUIVO` char(8) NOT NULL,
  `DC0NOME` char(24) DEFAULT NULL,
  `DC0USRBLQ` char(3) DEFAULT '',
  `DC0HORBLQ` datetime NOT NULL DEFAULT '1899-12-30 00:00:00',
  `DC0COMBLQ` char(30) DEFAULT '',
  `DC0ACESSO` decimal(1,0) DEFAULT '0',
  `DC0NAOIMP` decimal(1,0) DEFAULT '0',
  `DC0NAOEXP` decimal(1,0) DEFAULT '0',
  `DC0CONEXAO` decimal(1,0) DEFAULT '0',
  `DC0TIPO` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`DC0ARQUIVO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`dc1`;
CREATE TABLE  `oryxsupport`.`dc1` (
  `DC1CAMPO` char(10) NOT NULL,
  `DC1NOME` char(24) DEFAULT '',
  `DC1ARQUIVO` char(8) DEFAULT '',
  `DC1ARQPAI` char(8) DEFAULT '',
  `DC1CAMPAI` char(10) DEFAULT '',
  `DC1ASCEND` char(120) DEFAULT '',
  `DC1TIPO` char(1) DEFAULT '',
  `DC1TAMANHO` decimal(3,0) DEFAULT '0',
  `DC1DECIMAL` decimal(1,0) DEFAULT '0',
  `DC1ESPACO` decimal(10,0) DEFAULT '0',
  `DC1FORMATO` decimal(1,0) DEFAULT '0',
  `DC1NULO` decimal(1,0) DEFAULT '0',
  `DC1CHAVE` decimal(1,0) DEFAULT '0',
  `DC1AJUDA` char(254) DEFAULT '',
  `DC1ZOOM` char(8) DEFAULT '',
  `DC1EDICAO` decimal(1,0) DEFAULT '0',
  `DC1ULTIMO` char(12) DEFAULT '',
  PRIMARY KEY (`DC1CAMPO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`esm`;
CREATE TABLE  `oryxsupport`.`esm` (
  `ESMESTAB` int(11) NOT NULL,
  `ESMMODULO` int(11) NOT NULL,
  `ESMSESSOES` decimal(4,0) DEFAULT '0',
  PRIMARY KEY (`ESMESTAB`,`ESMMODULO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`est`;
CREATE TABLE  `oryxsupport`.`est` (
  `ESTESTAB` int(11) NOT NULL AUTO_INCREMENT,
  `ESTCPFCNPJ` char(14) DEFAULT '',
  `ESTNOME` char(20) DEFAULT '',
  `ESTCLIENTE` char(14) DEFAULT '',
  `ESTCAMPDV` char(255) DEFAULT '',
  `ESTCAMORYX` char(255) DEFAULT '',
  `ESTDATAATU` datetime DEFAULT '1899-12-30 00:00:00',
  `ESTIPINTER` char(15) DEFAULT '',
  `ESTIPEXTER` char(15) DEFAULT '',
  `ESTPORGAT` char(4) DEFAULT '',
  `ESTPORSER` char(4) DEFAULT '',
  `ESTPORSIT` char(4) DEFAULT '',
  `ESTPORGATE` char(4) DEFAULT '',
  `ESTPORSITE` char(4) DEFAULT '',
  `ESTMATRIZ` decimal(1,0) DEFAULT '0',
  `ESTSERVER` char(15) DEFAULT '',
  `ESTESQUEMA` char(20) DEFAULT '',
  `ESTVERSAO` int(11) DEFAULT '0',
  `ESTVERNOME` char(15) DEFAULT '',
  `ESTESQPAI` char(15) DEFAULT '',
  `ESTCAMTERM` char(255) DEFAULT '',
  `ESTPDVMOD` char(10) DEFAULT '',
  PRIMARY KEY (`ESTESTAB`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`esv`;
CREATE TABLE  `oryxsupport`.`esv` (
  `ESVESTAB` int(11) NOT NULL,
  `ESVVERSAO` int(11) NOT NULL,
  `ESVAUTOM` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`ESVESTAB`,`ESVVERSAO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`lx8`;
CREATE TABLE  `oryxsupport`.`lx8` (
  `LX8CLIENTE` char(14) DEFAULT '',
  `LX8ESTAB` int(11) NOT NULL,
  `LX8PROCESS` decimal(1,0) DEFAULT '0',
  `LX8DATAINI` datetime DEFAULT '1899-12-30 00:00:00',
  `LX8DATAFIM` datetime DEFAULT '1899-12-30 00:00:00',
  `LX8INFO` text,
  `LX8ERRO` decimal(1,0) DEFAULT '0',
  KEY `MAIN` (`LX8CLIENTE`,`LX8ESTAB`,`LX8PROCESS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`mod`;
CREATE TABLE  `oryxsupport`.`mod` (
  `MODMODULO` int(11) NOT NULL AUTO_INCREMENT,
  `MODNOME` char(20) DEFAULT '',
  `MODTIPO` decimal(2,0) DEFAULT '0',
  `MODABERT` datetime DEFAULT '1899-12-30 00:00:00',
  PRIMARY KEY (`MODMODULO`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`pd0`;
CREATE TABLE  `oryxsupport`.`pd0` (
  `PD0TERMINA` int(11) NOT NULL AUTO_INCREMENT,
  `PD0CLIENTE` char(14) DEFAULT '',
  `PD0NOME` char(50) DEFAULT '',
  `PD0SERVER` decimal(1,0) DEFAULT '0',
  `PD0VERSAO` char(15) DEFAULT '',
  PRIMARY KEY (`PD0TERMINA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`scr`;
CREATE TABLE  `oryxsupport`.`scr` (
  `SCRSCRIPT` int(11) NOT NULL AUTO_INCREMENT,
  `SCRMODULO` int(11) NOT NULL,
  `SCRVERSAO` int(11) NOT NULL,
  `SCRQUERY` mediumtext,
  PRIMARY KEY (`SCRSCRIPT`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `oryxsupport`.`ved`;
CREATE TABLE  `oryxsupport`.`ved` (
  `VEDVERSAO` int(11) NOT NULL,
  `VEDMODULO` int(11) NOT NULL,
  PRIMARY KEY (`VEDVERSAO`,`VEDMODULO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- foi pra o projeto
DROP TABLE IF EXISTS `oryxsupport`.`ver`;
CREATE TABLE  `oryxsupport`.`ver` (
  `VERVERSAO` int(11) NOT NULL AUTO_INCREMENT,
  `VERNOME` char(15) DEFAULT '',
  `VERLIBERAC` datetime DEFAULT '1899-12-30 00:00:00',
  `VERVALIDAD` datetime DEFAULT '1899-12-30 00:00:00',
  PRIMARY KEY (`VERVERSAO`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;